---
title: "Untitled"
author: "MariaProkofieva"
date: "13/06/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(skimr)
library(tibble)
```

```{r}
#let's load the files - you can see instruction on how to load also on the github page
# https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-05-26/readme.md

#we will be using the second dataset boston_coctails for this tutorial
# you can have your own time with coctails dataset later!
cocktails <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/cocktails.csv')
boston_cocktails <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/boston_cocktails.csv')

#let's have a quick look at the data 
# this gives us the first 20 rows of the dataset
head(boston_cocktails, 20)

#we can also have a fill of data types used there using summary function or skim from skimr library
#make sure to install it first and load it (see above)
summary(boston_cocktails)
skim(boston_cocktails) # much more explanatory and easy to use!
  
# let's see how many different categories we have and count drinks in each

boston_cocktails%>% 
   distinct(name, category) %>%
   count(category, sort=TRUE) 
 # as it looks like there are quite a view categories with only one name, 
 # we can lump them up together using fct_lump

test<-boston_cocktails %>% 
 # count (category) %>%
  mutate(number=fct_lump_n(category, 5),
         ingredient=fct_lump(ingredient, 3) %>%
  count(number)
 
   mutate(category=fct_lump(category, 5))
 
 

 boston_cocktails%>% 
   count(name, sort=TRUE)%>%
   head(20)%>%
   mutate(ingredient=fct_reorder(ingredient, n))%>%
   ggplot(aes(n, ingredient))%>%
   geom_col()
 

 boston_cocktails %>% 
   count(category, ingredient, name="cat") %>%
   mutate(ingredient=fct_reorder(ingredient,cat, .desc=FALSE)) %>%
  head(10)%>%
   ggplot(aes(cat, ingredient))+
   geom_col()+
  labs(title="most common ingredients")
  

 cocta   
 
```